#!/usr/bin/env bash
#Accepts a string as an argument and displays "is the host on the network" if no argument is passed.

if [ "$#" -eq 0 ]
then

  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"

else

  ping -c 5 "$1"

fi
