#!/bin/bash
# Define the server address and connect to it in the next line
SERVER="34.229.55.202"
# Use ssh to connect with the specified private key and user
ssh -i ~/.ssh/school -o User=ubuntu "$SERVER"